services:
  web:
    image: ghcr.io/bindzo8in/yash-organics:latest
    container_name: yash-organics
    restart: unless-stopped

    init: true

    env_file:
      - .env

    networks:
      - web_network

networks:
  web_network:
    external: true